import numpy as np
import logging
from typing import Optional, List
from PIL import Image
import torch
from transformers import CLIPProcessor, CLIPModel
from app.models.schemas import ActivityResult

logger = logging.getLogger(__name__)

class ActivityService:
    """
    ActivityService performs zero-shot classification to verify if an ongoing
    scene activity is authorized or unauthorized.
    It leverages the OpenAI CLIP (Contrastive Language-Image Pre-training) model
    which can compare images against text descriptions directly or compare 
    text captions against a set of predefined labels (text-to-text matching).
    """
    def __init__(self):
        """
        Initializes the CLIP model and processor.
        Detects GPU (CUDA/MPS) or falls back to CPU.
        """
        logger.info("Initializing ActivityService (CLIP)...")
        self.device = "cuda" if torch.cuda.is_available() else "mps" if torch.backends.mps.is_available() else "cpu"
        self.model_id = "openai/clip-vit-base-patch32"
        self.processor = CLIPProcessor.from_pretrained(self.model_id)
        self.model = CLIPModel.from_pretrained(self.model_id).to(self.device)

    def analyze(self, 
                image: Optional[np.ndarray] = None, 
                caption: Optional[str] = None,
                allowed_activities: Optional[List[str]] = None,
                unauthorized_activities: Optional[List[str]] = None) -> ActivityResult:
        """
        Determines the most likely activity based on image content OR text caption.
        Uses CLIP to find the highest similarity match from the provided activity lists.
        
        Args:
            image (Optional[np.ndarray]): The raw BGR image array (optional).
            caption (Optional[str]): A text description of the scene (optional).
            allowed_activities (Optional[List[str]]): List of permissible activities.
            unauthorized_activities (Optional[List[str]]): List of forbidden activities.
            
        Returns:
            ActivityResult: Includes the identified activity label, its authorization status, and confidence score.
        """
        allowed = allowed_activities or []
        unauthorized = unauthorized_activities or []
        all_activities = allowed + unauthorized

        # If no policy rules are defined, we cannot classify the intent.
        if not all_activities:
            logger.warning("No activities provided for classification.")
            return ActivityResult(activity="None defined", status="UNAUTHORIZED", confidence=0.0)

        probs = []
        # BRANCH 1: Visual Classification (CLIP Image-Text comparison)
        if image is not None:
            # Prepare image for CLIP
            rgb_image = image[:, :, ::-1]
            pil_image = Image.fromarray(rgb_image)
            
            # CLIP finds which text prompt best matches the visual features of the image.
            inputs = self.processor(text=all_activities, images=pil_image, return_tensors="pt", padding=True).to(self.device)
            outputs = self.model(**inputs)
            
            # Extract probability distribution across the activity labels.
            logits_per_image = outputs.logits_per_image
            probs = logits_per_image.softmax(dim=1).cpu().detach().numpy()[0]
            
        # BRANCH 2: Semantic Verification (CLIP Text-Text comparison)
        # Useful if image isn't available or we want to verify the caption generated by SceneService.
        elif caption is not None:
            # Generate shared embeddings for the caption and all possible activity labels.
            inputs = self.processor(text=[caption] + all_activities, return_tensors="pt", padding=True).to(self.device)
            text_features = self.model.get_text_features(**inputs)
            # Normalize embeddings to calculate cosine similarity via dot product.
            text_features = text_features / text_features.norm(dim=-1, keepdim=True)
            
            caption_embed = text_features[0]
            rules_embeds = text_features[1:]
            
            # Calculate similarity scores between the caption and each rule.
            similarities = (rules_embeds @ caption_embed.T).squeeze(0)
            probs = similarities.softmax(dim=0).cpu().detach().numpy()
            
        else:
            return ActivityResult(activity="No input", status="UNAUTHORIZED", confidence=0.0)
            
        # Map back to the best fitting activity label
        best_idx = np.argmax(probs)
        best_activity = all_activities[best_idx]
        confidence = float(probs[best_idx])
        
        # Determine final authorization status based on grouping.
        status = "AUTHORIZED" if best_activity in allowed else "UNAUTHORIZED"
        
        logger.info(f"Classified activity as: {best_activity} ({status}) with {confidence:.2f} confidence.")
        return ActivityResult(
            activity=best_activity,
            status=status,
            confidence=confidence
        )
